config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  
  get     '/about',   to: 'static_pages#about'
  
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :users
  
  resources :tabs do
    resources :ratings, only: [:create, :update, :destroy]
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # songs, albums, and artists will all be created from tab creation
  # therefore, we don't need a 'new' route
  resources :artists,             except: :new
  
  resources :songs,               except: :new
  
  resources :albums,              except: :new
end

app/models/user.rb
class User < ApplicationRecord
  # user can submit many tabs
  has_many :tabs
  
  # user can submit many ratings to tabs
  # when user is destroyed, their ratings are also destroyed
  has_many :ratings, dependent: :destroy
  
  attr_accessor :remember_token, :activation_token, :reset_token
  
  before_create :create_activation_digest
  
  before_save :downcase_email 
  
  # name validation
  validates :name, presence: true, length: { maximum: 50 }
  
  # email validation
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-.]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  # password functionality, validation                
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest) == token
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  def tabfeed
    Tab.where("user_id = ?", id)
  end
  
  def rate(tab, value)
    ratings.create!(tab: tab, value: value)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: [:index, :destroy]
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.where(activated: true);
  end
  
  def show
    @user = User.find(params[:id])
    @tabs = tabViewQuery(@user.tabs)
    redirect_to root_url and return unless @user.activated
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash.now[:info] = "Thanks for joining Intuitab! To activate your account, read the email sent to #{@user.email} and follow the instructions within!"
      redirect_to root_url
    else 
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User successfully deleted!"
    redirect_to users_url
  end
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for(user)
    image_tag(user.avatar, alt: user.name, class: "avatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Account settings') %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, edit_user_path(@user)) %> 

<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<% users_json = User.includes(:tabs).map { |user| user.as_json.merge({tabs: user.tabs.as_json}) } %>

<%= react_component 'Users', {  data:       users_json,
                                usersPath:  users_path} %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.tabs.any? %>
      <%= render 'shared/tabs_component', object: @tabs %>
    <% end %>
  </div>
</div>