config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  
  get     '/about',   to: 'static_pages#about'
  
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  
  resources :users
  
  resources :tabs do
    resources :ratings, only: [:create, :update, :destroy]
  end
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  # songs, albums, and artists will all be created from tab creation
  # therefore, we don't need a 'new' route
  resources :artists,             except: :new
  
  resources :songs,               except: :new
  
  resources :albums,              except: :new
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Made by Nick Anderson (:
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Intuitab", root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <%= render 'layouts/searchbar' %>
            <ul class="nav navbar-nav navbar-right">
                <%= active_link_to "Home", root_path, wrap_tag: :li, active: :exclusive %>
                <%= active_link_to "Tabs", tabs_path, wrap_tag: :li %>
                <%= active_link_to "Artists", artists_path, wrap_tag: :li %>
                <%= active_link_to "Albums", albums_path, wrap_tag: :li %>
                <%= active_link_to "Songs", songs_path, wrap_tag: :li %>
                <% if logged_in? %>
                    <%= active_link_to "Users", users_path, wrap_tag: :li, active: :exclusive %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: :delete %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <%= active_link_to "Log in", login_path, wrap_tag: :li %>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

app/views/layouts/_searchbar.html.erb
<%= form_tag(tabs_path, :method => "get", id: "search-form") do %>
  <div class="col-sm-3 float-left">
    <div class="navbar-form input-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Tabs", class: 'form-control' %>
        <span class="input-group-btn">
          <%= button_tag "Search", class: 'btn btn-default', :name => nil do %>
            <i class="glyphicon glyphicon-search"></i>
          <% end %>
        </span>
    </div>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>